/**
 * Service Worker — offline strategy.
 *
 * Person 4 implements this file.
 *
 * This file is managed by vite-plugin-pwa (via Workbox).
 * Configure caching strategies in vite.config.js → workbox options.
 *
 * Responsibilities (see docs/OFFLINE.md):
 * 1. Cache application shell (HTML, CSS, JS)
 * 2. Cache emergency static content
 * 3. Cache last-known risk zone GeoJSON (network-first with fallback)
 * 4. Expose cached data age to the frontend so the UI can show "last updated" timestamps
 *
 * ⚠️  Important: this file will be auto-generated by Workbox if using
 *     vite-plugin-pwa's generateSW strategy. Only write custom logic here
 *     if using the injectManifest strategy. Decide and document in OFFLINE.md.
 */

// TODO (Person 4): implement caching strategy
// TODO (Person 4): implement offline fallback for /api/risk-zones
// TODO (Person 4): expose is_live flag to the frontend
